name = "my-project"
main = "src/index.ts"
compatibility_date = "2023-08-09"

kv_namespaces = [
  { binding = "TRACKING", id = "<NAMESPACE_ID_HERE>" }
]

[vars]
SOURCE_QUERY_PARAM = "s"

PNG_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII="

GA4_MEASUREMENT_ID = "<GA4_MEASUREMENT_ID_HERE>"
GA4_API_SECRET = "<GA4_API_SECRET_HERE>"
GA4_EVENT_NAME = "cloudflare_worker_event"